---
title: "rct2otrbounds"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rct2otrbounds}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rct2otrbounds)
```

```{r}
treatment_effect_heterogeneity_bound(
  s2_1 = 6.53^2,
  s2_0 = 7.52^2,
  n_1 = 114,
  n_0 = 126,
  mean_1 = 10.73,
  mean_0 = 11.94,
  m = 0,
  M = 52,
  level = 0.95,
  bounded_outcome = TRUE,
  conf.int = TRUE
)


```

```{r}

closed_form_ideal_rule_benefit(
  s2_1 = 6.53^2,
  s2_0 = 7.52^2,
  n_1 = 114,
  n_0 = 126,
  mean_1 = 10.73,
  mean_0 = 11.94,
  m = 0,
  M = 52,
  level = 0.95,
  bounded_outcome = TRUE,
  conf.upper = TRUE
)

```

```{r}

lp_ideal_rule_benefit(
  s2_1 = 6.53^2,
  s2_0 = 7.52^2,
  n_1 = 114,
  n_0 = 126,
  mean_1 = 10.73,
  mean_0 = 11.94,
  m = 0,
  M = 52,
  level = 0.95,
  conf.upper = TRUE,
  scale = "lower"
)

```

```{r}

plot_ideal_rule_benefits(
    s2_1 = 6.53^2,
  s2_0 = 7.52^2,
  n_1 = 114,
  n_0 = 126,
  mean_1 = 10.73,
  mean_0 = 11.94,
  m = 0,
  M = 52,
  level = 0.95,
  bounded_outcome = TRUE,
  conf.upper = TRUE,
  mean_1_s = 10.73,
  mean_0_s = 11.94, 
  s_prop_low = 0.1,
  s_prop_high = 0.9
)

```

